# frozen_string_literal: true

require "cure/generator/base_generator"
require "cure/generator/hex_generator"
require "cure/generator/case_generator"
require "cure/generator/character_generator"
require "cure/generator/faker_generator"
require "cure/generator/guid_generator"
require "cure/generator/number_generator"
require "cure/generator/placeholder_generator"
require "cure/generator/redact_generator"
require "cure/generator/variable_generator"
require "cure/generator/eval_generator"
require "cure/generator/erb_generator"
require "cure/generator/proc_generator"
require "cure/generator/static_generator"
