#!/usr/bin/env ruby

require "cure/cli/command"

short_hand = {
  "n" => "new",
  "r" => "run"
}

command = ARGV.shift
command = short_hand[command] || command

Cure::Cli::Command.invoke(command, ARGV)